### ISSUE TITLE
Soportar agregar reporte Libre

### ISSUE THREAD

**Issue by farodrig** [InspectorIncognito/server#18]
Se debe soportar la posibilidad de crear un reporte libre.
Este consta de un texto de tamaño indefinido y de una imagen en base 64 para ser decodificada.
Los datos son mandados por POST, no por GET.
Se debe guardar en la BD.
Idealmente, tambien vendría la extensión.

**Comment by farodrig** [comment]
Ya fue agregada URL que debería aceptar esto, guardar la información en la BD y el archivo en una carpeta por defecto.

**Comment by farodrig** [comment]
Falta testear con la aplicación.

**Comment by amermelao** [comment]
se agrego el usurio de apache al grupo, para que pueda crera archivos en la carpeta media
