### ISSUE TITLE
Orientación del bus debería considerar la posición del paradero

### ISSUE THREAD

**Issue by felipinbombin** [InspectorIncognito/server#25]
La cara del bus debería mirar al paradero cuando su movimiento se define "hacia arriba" o "hacia abajo" con respecto a la orientación en un mapa.

**Forma de reproducir:**
No hay una forma directa de hacerlo. Una alternativa es buscar paraderos donde los buses se muevan hacia abajo cuando su paradero se encuentra a la izquierda de su posición. Unos ejemplos de esto pueden ser los siguientes paraderos:
- PA452 cuando la 509 se encuentra por la calle san ignacio

**Comportamiento esperado:**
Cuando un bus se mueve  hacia arriba o hacia abajo en la pantalla, la orientación siempre debería apuntar al paradero.

**Posible solución:**
Agregar más validaciones y condiciones sobre los datos que permiten determinar el sentido del bus.

**MUST:**
Agregar test a la bateria que verifique que el comportamiento es el deseado.

**Comment by aantoine** [comment]
Related: #

**Comment by felipinbombin** [comment]
Problema corregido. Se agregan tests que verifican su comportamiento.

commits relacionados:
[9ae11c80baebafe41f1a6f1b3a1c26a82b345726](https://github.com/InspectorIncognito/server/commit/9ae11c80baebafe41f1a6f1b3a1c26a82b345726)
[498080cbfc4ba7dd82eb789ec14296f7495492d7](https://github.com/InspectorIncognito/server/commit/498080cbfc4ba7dd82eb789ec14296f7495492d7)
