### ISSUE TITLE
Modificar estimación de la posición del bus.

### ISSUE THREAD

**Issue by farodrig** [InspectorIncognito/server#6]
Dado que los datos a cargar deben soportar el sentido de los servicios, se debe modificar el algoritmo de estimación de la posición de la micro.

**Comment by farodrig** [comment]
Se modificó el algoritmo, se debe testear una vez que los datos esten cargados en el servidor.

**Comment by farodrig** [comment]
Los nuevos datos entregados tampoco eran correctos, de manera que no se ha podido cerrar esta issue.

**Comment by amermelao** [comment]
hay nuevos datos, que estan correcotos

**Comment by amermelao** [comment]
Se cargo los datos nuevos a amzon y se probo con algunos paraderos que sea correcto.
